#应用名
spring:
  application:
    name: cloud-provider-movie
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url:  http://127.0.0.1:9411/
#端口号
server:
  port: 7000
  servlet:
    context-path: /movie
eureka:
  instance:
    #注册到注册中心时当前实例的ip地址
    ip-address: 192.168.92.1
    #支持注册中心允许其他的服务使用当前服务的ip地址
    prefer-ip-address: true
  client:
    service-url:
      #指定自己要注册的注册中心的唯一标志
      defaultZone: http://127.0.0.1:8761/eureka/